/*

 * Copyright 2006 Jason Stredwick.

 * Distributed under the Boost Software License, Version 1.0. (See
 * LICENSE information at the bottom of this file or the copy at
 * http://www.boost.org/LICENSE_1_0.txt)

 */

#ifndef __Ptr_h__
#define __Ptr_h__

template <typename T>
class Ptr
{
private:
  T *d_ptr;

public:
  Ptr(void) : d_ptr(0) { return; }
  Ptr(T *p) : d_ptr(p) { return; }
  Ptr(const Ptr<T> &p) : d_ptr(p.d_ptr) { return; }
  ~Ptr(void) { d_ptr = 0; return; }

  const Ptr<T> &operator=(const Ptr<T> &p)
  {
    d_ptr = p.d_ptr;
    return *this;
  }

  const Ptr<T> &operator=(const T * const p)
  {
    d_ptr = p;
    return *this;
  }

  // Address operator
  const T * const * operator&() const { return &d_ptr; }
        T ** operator&()       { return &d_ptr; }

  // Cast operators
  operator const T *() const { return d_ptr; }
  operator       T *()       { return d_ptr; }

  // Dereference operators
  const T &operator*(void) const { return *d_ptr; }
        T &operator*(void)       { return *d_ptr; }

  const Ptr<T> *Address(void) const { return this; }
        Ptr<T> *Address(void)       { return this; }

  const bool IsNull(void) const { return d_ptr == 0; }
};

#endif

/*

 * Boost Software License - Version 1.0 - August 17th, 2003

 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:

 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.

 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.

 */
