/****************************************************************************
** Form implementation generated from reading ui file 'UI/bindingform.ui'
**
** Created: Mon Oct 11 23:36:20 2004
**      by: The User Interface Compiler ($Id: bindingform.cpp,v 1.1.1.1 2004/10/14 22:49:33 jason Exp $)
**
** WARNING! All changes made in this file will be lost!
****************************************************************************/

#include "bindingform.h"

#include <qvariant.h>
#include <qbuttongroup.h>
#include <qcheckbox.h>
#include <qlabel.h>
#include <qpushbutton.h>
#include <qslider.h>
#include <qtabwidget.h>
#include <qwidget.h>
#include <qlayout.h>
#include <qtooltip.h>
#include <qwhatsthis.h>

/* 
 *  Constructs a BindingForm as a child of 'parent', with the 
 *  name 'name' and widget flags set to 'f'.
 *
 *  The dialog will by default be modeless, unless you set 'modal' to
 *  TRUE to construct a modal dialog.
 */
BindingForm::BindingForm( QWidget* parent, const char* name, bool modal, WFlags fl )
    : QDialog( parent, name, modal, fl )

{
    if ( !name )
	setName( "BindingForm" );
    setPaletteForegroundColor( QColor( 0, 255, 0 ) );
    setPaletteBackgroundColor( QColor( 0, 0, 0 ) );

    CancelButton = new QPushButton( this, "CancelButton" );
    CancelButton->setGeometry( QRect( 391, 570, 80, 50 ) );
    CancelButton->setPaletteForegroundColor( QColor( 0, 255, 0 ) );
    CancelButton->setPaletteBackgroundColor( QColor( 11, 50, 89 ) );

    DoneButton = new QPushButton( this, "DoneButton" );
    DoneButton->setGeometry( QRect( 10, 570, 80, 50 ) );
    DoneButton->setPaletteForegroundColor( QColor( 0, 255, 0 ) );
    DoneButton->setPaletteBackgroundColor( QColor( 11, 50, 89 ) );

    ApplyButton = new QPushButton( this, "ApplyButton" );
    ApplyButton->setGeometry( QRect( 90, 570, 80, 50 ) );
    ApplyButton->setPaletteForegroundColor( QColor( 0, 255, 0 ) );
    ApplyButton->setPaletteBackgroundColor( QColor( 11, 50, 89 ) );

    LoadDefaultsButton = new QPushButton( this, "LoadDefaultsButton" );
    LoadDefaultsButton->setGeometry( QRect( 280, 570, 110, 50 ) );
    LoadDefaultsButton->setPaletteForegroundColor( QColor( 0, 255, 0 ) );
    LoadDefaultsButton->setPaletteBackgroundColor( QColor( 11, 50, 89 ) );

    SaveDefaultsButton = new QPushButton( this, "SaveDefaultsButton" );
    SaveDefaultsButton->setGeometry( QRect( 170, 570, 110, 50 ) );
    SaveDefaultsButton->setPaletteForegroundColor( QColor( 0, 255, 0 ) );
    SaveDefaultsButton->setPaletteBackgroundColor( QColor( 11, 50, 89 ) );

    KeyBinder = new QTabWidget( this, "KeyBinder" );
    KeyBinder->setGeometry( QRect( 10, 10, 460, 550 ) );
    KeyBinder->setPaletteForegroundColor( QColor( 0, 255, 0 ) );
    KeyBinder->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );

    system = new QWidget( KeyBinder, "system" );

    SystemButtonGroup = new QButtonGroup( system, "SystemButtonGroup" );
    SystemButtonGroup->setGeometry( QRect( 20, 30, 140, 190 ) );
    SystemButtonGroup->setLineWidth( 0 );
    SystemButtonGroup->setAlignment( int( QButtonGroup::AlignAuto ) );

    QuitButton = new QPushButton( SystemButtonGroup, "QuitButton" );
    QuitButton->setGeometry( QRect( 1, 1, 80, 37 ) );
    QuitButton->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    QPalette pal;
    QColorGroup cg;
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setDisabled( cg );
    QuitButton->setPalette( pal );
    SystemButtonGroup->insert( QuitButton, 0 );

    HelpButton = new QPushButton( SystemButtonGroup, "HelpButton" );
    HelpButton->setGeometry( QRect( 1, 44, 80, 37 ) );
    HelpButton->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setDisabled( cg );
    HelpButton->setPalette( pal );
    SystemButtonGroup->insert( HelpButton, 1 );

    GridButton = new QPushButton( SystemButtonGroup, "GridButton" );
    GridButton->setGeometry( QRect( 0, 90, 130, 30 ) );
    GridButton->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setDisabled( cg );
    GridButton->setPalette( pal );

    SystemButtonGroup2 = new QButtonGroup( system, "SystemButtonGroup2" );
    SystemButtonGroup2->setGeometry( QRect( 310, 20, 130, 180 ) );
    SystemButtonGroup2->setLineWidth( 0 );

    GridKey = new QLabel( SystemButtonGroup2, "GridKey" );
    GridKey->setGeometry( QRect( 10, 100, 120, 30 ) );
    GridKey->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    GridKey->setAlignment( int( QLabel::AlignVCenter | QLabel::AlignLeft ) );

    HelpKey = new QLabel( SystemButtonGroup2, "HelpKey" );
    HelpKey->setGeometry( QRect( 10, 50, 108, 40 ) );
    HelpKey->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    HelpKey->setAlignment( int( QLabel::AlignVCenter | QLabel::AlignLeft ) );

    QuitKey = new QLabel( SystemButtonGroup2, "QuitKey" );
    QuitKey->setGeometry( QRect( 10, 10, 108, 36 ) );
    QuitKey->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    QuitKey->setAlignment( int( QLabel::AlignVCenter | QLabel::AlignLeft ) );
    KeyBinder->insertTab( system, "" );

    mouse = new QWidget( KeyBinder, "mouse" );

    QuitKey_2 = new QLabel( mouse, "QuitKey_2" );
    QuitKey_2->setGeometry( QRect( 230, 0, 94, 20 ) );

    MouseButtonGroup = new QButtonGroup( mouse, "MouseButtonGroup" );
    MouseButtonGroup->setGeometry( QRect( 30, 30, 150, 210 ) );
    MouseButtonGroup->setLineWidth( 0 );

    MouseToggleButton = new QPushButton( MouseButtonGroup, "MouseToggleButton" );
    MouseToggleButton->setGeometry( QRect( 11, 3, 118, 37 ) );
    MouseToggleButton->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setDisabled( cg );
    MouseToggleButton->setPalette( pal );
    MouseButtonGroup->insert( MouseToggleButton, 0 );

    FreeLookButton = new QPushButton( MouseButtonGroup, "FreeLookButton" );
    FreeLookButton->setGeometry( QRect( 11, 48, 118, 37 ) );
    FreeLookButton->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setDisabled( cg );
    FreeLookButton->setPalette( pal );
    MouseButtonGroup->insert( FreeLookButton, 1 );

    TextLabel1 = new QLabel( MouseButtonGroup, "TextLabel1" );
    TextLabel1->setGeometry( QRect( 11, 132, 138, 32 ) );

    MouseSpeedMultiplier = new QSlider( MouseButtonGroup, "MouseSpeedMultiplier" );
    MouseSpeedMultiplier->setGeometry( QRect( 11, 170, 138, 29 ) );
    MouseSpeedMultiplier->setOrientation( QSlider::Horizontal );
    MouseSpeedMultiplier->setTickmarks( QSlider::Right );
    MouseSpeedMultiplier->setTickInterval( 10 );

    InvertMouse = new QCheckBox( MouseButtonGroup, "InvertMouse" );
    InvertMouse->setGeometry( QRect( 11, 101, 138, 25 ) );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, QColor( 11, 50, 89) );
    cg.setColor( QColorGroup::Light, QColor( 17, 75, 133) );
    cg.setColor( QColorGroup::Midlight, QColor( 14, 62, 111) );
    cg.setColor( QColorGroup::Dark, QColor( 6, 25, 44) );
    cg.setColor( QColorGroup::Mid, QColor( 7, 33, 59) );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, black );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, black );
    cg.setColor( QColorGroup::HighlightedText, white );
    cg.setColor( QColorGroup::Link, QColor( 0, 0, 255) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 255, 0, 255) );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, QColor( 11, 50, 89) );
    cg.setColor( QColorGroup::Light, QColor( 17, 75, 133) );
    cg.setColor( QColorGroup::Midlight, QColor( 13, 57, 102) );
    cg.setColor( QColorGroup::Dark, QColor( 6, 25, 44) );
    cg.setColor( QColorGroup::Mid, QColor( 7, 33, 59) );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, black );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, black );
    cg.setColor( QColorGroup::HighlightedText, white );
    cg.setColor( QColorGroup::Link, QColor( 0, 0, 255) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 255, 0, 255) );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, QColor( 11, 50, 89) );
    cg.setColor( QColorGroup::Light, QColor( 17, 75, 133) );
    cg.setColor( QColorGroup::Midlight, QColor( 13, 57, 102) );
    cg.setColor( QColorGroup::Dark, QColor( 6, 25, 44) );
    cg.setColor( QColorGroup::Mid, QColor( 7, 33, 59) );
    cg.setColor( QColorGroup::Text, black );
    cg.setColor( QColorGroup::BrightText, white );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, white );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, black );
    cg.setColor( QColorGroup::HighlightedText, white );
    cg.setColor( QColorGroup::Link, QColor( 0, 0, 255) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 255, 0, 255) );
    pal.setDisabled( cg );
    InvertMouse->setPalette( pal );

    MouseToggleKey = new QLabel( mouse, "MouseToggleKey" );
    MouseToggleKey->setGeometry( QRect( 241, 31, 118, 41 ) );
    MouseToggleKey->setAlignment( int( QLabel::AlignVCenter | QLabel::AlignLeft ) );

    FreeLookKey = new QLabel( mouse, "FreeLookKey" );
    FreeLookKey->setGeometry( QRect( 241, 78, 118, 41 ) );
    FreeLookKey->setAlignment( int( QLabel::AlignVCenter | QLabel::AlignLeft ) );
    KeyBinder->insertTab( mouse, "" );

    eyepoint = new QWidget( KeyBinder, "eyepoint" );

    EyepointButtonGroup2 = new QButtonGroup( eyepoint, "EyepointButtonGroup2" );
    EyepointButtonGroup2->setGeometry( QRect( 290, 20, 150, 410 ) );
    EyepointButtonGroup2->setLineWidth( 0 );
    EyepointButtonGroup2->setAlignment( int( QButtonGroup::AlignTop ) );

    MoveRightKey = new QLabel( EyepointButtonGroup2, "MoveRightKey" );
    MoveRightKey->setGeometry( QRect( 0, 130, 138, 36 ) );
    MoveRightKey->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    MoveRightKey->setLineWidth( 0 );
    MoveRightKey->setAlignment( int( QLabel::AlignCenter ) );

    MoveUpKey = new QLabel( EyepointButtonGroup2, "MoveUpKey" );
    MoveUpKey->setGeometry( QRect( 0, 250, 138, 37 ) );
    MoveUpKey->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    MoveUpKey->setLineWidth( 0 );
    MoveUpKey->setAlignment( int( QLabel::AlignCenter ) );

    MoveLeftKey = new QLabel( EyepointButtonGroup2, "MoveLeftKey" );
    MoveLeftKey->setGeometry( QRect( 0, 90, 138, 36 ) );
    MoveLeftKey->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    MoveLeftKey->setLineWidth( 0 );
    MoveLeftKey->setAlignment( int( QLabel::AlignCenter ) );

    TurnLeftKey = new QLabel( EyepointButtonGroup2, "TurnLeftKey" );
    TurnLeftKey->setGeometry( QRect( 0, 170, 138, 37 ) );
    TurnLeftKey->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    TurnLeftKey->setLineWidth( 0 );
    TurnLeftKey->setAlignment( int( QLabel::AlignCenter ) );

    TurnRightKey = new QLabel( EyepointButtonGroup2, "TurnRightKey" );
    TurnRightKey->setGeometry( QRect( 0, 210, 138, 37 ) );
    TurnRightKey->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    TurnRightKey->setLineWidth( 0 );
    TurnRightKey->setAlignment( int( QLabel::AlignCenter ) );

    MoveDownKey = new QLabel( EyepointButtonGroup2, "MoveDownKey" );
    MoveDownKey->setGeometry( QRect( 0, 290, 138, 36 ) );
    MoveDownKey->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    MoveDownKey->setLineWidth( 0 );
    MoveDownKey->setAlignment( int( QLabel::AlignCenter ) );

    PitchUpKey = new QLabel( EyepointButtonGroup2, "PitchUpKey" );
    PitchUpKey->setGeometry( QRect( 0, 330, 138, 36 ) );
    PitchUpKey->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    PitchUpKey->setLineWidth( 0 );
    PitchUpKey->setAlignment( int( QLabel::AlignCenter ) );

    PitchDownKey = new QLabel( EyepointButtonGroup2, "PitchDownKey" );
    PitchDownKey->setGeometry( QRect( 0, 370, 138, 36 ) );
    PitchDownKey->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    PitchDownKey->setLineWidth( 0 );
    PitchDownKey->setAlignment( int( QLabel::AlignCenter ) );

    MoveBackwardKey = new QLabel( EyepointButtonGroup2, "MoveBackwardKey" );
    MoveBackwardKey->setGeometry( QRect( 0, 50, 138, 37 ) );
    MoveBackwardKey->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    MoveBackwardKey->setLineWidth( 0 );
    MoveBackwardKey->setAlignment( int( QLabel::AlignCenter ) );

    MoveForwardKey = new QLabel( EyepointButtonGroup2, "MoveForwardKey" );
    MoveForwardKey->setGeometry( QRect( 0, 10, 138, 36 ) );
    MoveForwardKey->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    MoveForwardKey->setLineWidth( 0 );
    MoveForwardKey->setAlignment( int( QLabel::AlignCenter ) );

    EyepointButtonGroup = new QButtonGroup( eyepoint, "EyepointButtonGroup" );
    EyepointButtonGroup->setGeometry( QRect( 30, 20, 120, 420 ) );
    EyepointButtonGroup->setLineWidth( 0 );

    ForwardButton = new QPushButton( EyepointButtonGroup, "ForwardButton" );
    ForwardButton->setGeometry( QRect( 0, 10, 108, 37 ) );
    ForwardButton->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setDisabled( cg );
    ForwardButton->setPalette( pal );
    EyepointButtonGroup->insert( ForwardButton, 0 );

    BackwardButton = new QPushButton( EyepointButtonGroup, "BackwardButton" );
    BackwardButton->setGeometry( QRect( 0, 50, 108, 37 ) );
    BackwardButton->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setDisabled( cg );
    BackwardButton->setPalette( pal );
    EyepointButtonGroup->insert( BackwardButton, 1 );

    LeftButton = new QPushButton( EyepointButtonGroup, "LeftButton" );
    LeftButton->setGeometry( QRect( 0, 90, 108, 37 ) );
    LeftButton->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setDisabled( cg );
    LeftButton->setPalette( pal );
    EyepointButtonGroup->insert( LeftButton, 2 );

    RightButton = new QPushButton( EyepointButtonGroup, "RightButton" );
    RightButton->setGeometry( QRect( 0, 130, 108, 37 ) );
    RightButton->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setDisabled( cg );
    RightButton->setPalette( pal );
    EyepointButtonGroup->insert( RightButton, 3 );

    TurnRightButton = new QPushButton( EyepointButtonGroup, "TurnRightButton" );
    TurnRightButton->setGeometry( QRect( 0, 210, 108, 37 ) );
    TurnRightButton->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setDisabled( cg );
    TurnRightButton->setPalette( pal );
    EyepointButtonGroup->insert( TurnRightButton, 5 );

    UpButton = new QPushButton( EyepointButtonGroup, "UpButton" );
    UpButton->setGeometry( QRect( 0, 250, 108, 37 ) );
    UpButton->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setDisabled( cg );
    UpButton->setPalette( pal );
    EyepointButtonGroup->insert( UpButton, 6 );

    DownButton = new QPushButton( EyepointButtonGroup, "DownButton" );
    DownButton->setGeometry( QRect( 0, 290, 108, 37 ) );
    DownButton->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setDisabled( cg );
    DownButton->setPalette( pal );
    EyepointButtonGroup->insert( DownButton, 7 );

    PitchUpButton = new QPushButton( EyepointButtonGroup, "PitchUpButton" );
    PitchUpButton->setGeometry( QRect( 0, 330, 108, 37 ) );
    PitchUpButton->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setDisabled( cg );
    PitchUpButton->setPalette( pal );
    EyepointButtonGroup->insert( PitchUpButton, 8 );

    PitchDownButton = new QPushButton( EyepointButtonGroup, "PitchDownButton" );
    PitchDownButton->setGeometry( QRect( 0, 370, 108, 37 ) );
    PitchDownButton->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setDisabled( cg );
    PitchDownButton->setPalette( pal );
    EyepointButtonGroup->insert( PitchDownButton, 9 );

    TurnLeftButton = new QPushButton( EyepointButtonGroup, "TurnLeftButton" );
    TurnLeftButton->setGeometry( QRect( 0, 170, 108, 37 ) );
    TurnLeftButton->setPaletteBackgroundColor( QColor( 0, 0, 0 ) );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setActive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setInactive( cg );
    cg.setColor( QColorGroup::Foreground, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Button, black );
    cg.setColor( QColorGroup::Light, black );
    cg.setColor( QColorGroup::Midlight, black );
    cg.setColor( QColorGroup::Dark, black );
    cg.setColor( QColorGroup::Mid, black );
    cg.setColor( QColorGroup::Text, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::BrightText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::ButtonText, QColor( 128, 128, 128) );
    cg.setColor( QColorGroup::Base, black );
    cg.setColor( QColorGroup::Background, black );
    cg.setColor( QColorGroup::Shadow, black );
    cg.setColor( QColorGroup::Highlight, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::HighlightedText, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::Link, QColor( 0, 255, 0) );
    cg.setColor( QColorGroup::LinkVisited, QColor( 0, 255, 0) );
    pal.setDisabled( cg );
    TurnLeftButton->setPalette( pal );
    EyepointButtonGroup->insert( TurnLeftButton, 4 );
    KeyBinder->insertTab( eyepoint, "" );
    languageChange();
    resize( QSize(484, 624).expandedTo(minimumSizeHint()) );

    // signals and slots connections
    connect( CancelButton, SIGNAL( clicked() ), this, SLOT( close() ) );
    connect( DoneButton, SIGNAL( clicked() ), this, SLOT( close() ) );

    // tab order
    setTabOrder( DoneButton, ApplyButton );
    setTabOrder( ApplyButton, CancelButton );
    setTabOrder( CancelButton, KeyBinder );
    setTabOrder( KeyBinder, QuitButton );
    setTabOrder( QuitButton, HelpButton );
    setTabOrder( HelpButton, MouseToggleButton );
    setTabOrder( MouseToggleButton, FreeLookButton );
    setTabOrder( FreeLookButton, InvertMouse );
    setTabOrder( InvertMouse, MouseSpeedMultiplier );
    setTabOrder( MouseSpeedMultiplier, ForwardButton );
    setTabOrder( ForwardButton, BackwardButton );
    setTabOrder( BackwardButton, LeftButton );
    setTabOrder( LeftButton, RightButton );
}

/*
 *  Destroys the object and frees any allocated resources
 */
BindingForm::~BindingForm()
{
    // no need to delete child widgets, Qt does it all for us
}

/*
 *  Sets the strings of the subwidgets using the current
 *  language.
 */
void BindingForm::languageChange()
{
    setCaption( tr( "Bindings" ) );
    CancelButton->setText( tr( "Cancel" ) );
    DoneButton->setText( tr( "Done" ) );
    ApplyButton->setText( tr( "Apply" ) );
    LoadDefaultsButton->setText( tr( "Load Defaults" ) );
    SaveDefaultsButton->setText( tr( "Save Defaults" ) );
    QToolTip::add( KeyBinder, tr( "Bindings" ) );
    QWhatsThis::add( KeyBinder, tr( "Bindings" ) );
    SystemButtonGroup->setTitle( QString::null );
    QuitButton->setText( tr( "Quit" ) );
    HelpButton->setText( tr( "Help" ) );
    GridButton->setText( tr( "Toggle Grid" ) );
    SystemButtonGroup2->setTitle( QString::null );
    GridKey->setText( QString::null );
    HelpKey->setText( QString::null );
    QuitKey->setText( QString::null );
    KeyBinder->changeTab( system, tr( "System" ) );
    QuitKey_2->setText( QString::null );
    MouseButtonGroup->setTitle( QString::null );
    MouseToggleButton->setText( tr( "Mouse Toggle" ) );
    FreeLookButton->setText( tr( "Free Look" ) );
    TextLabel1->setText( tr( "Mouse Speed" ) );
    InvertMouse->setText( tr( "Invert Mouse" ) );
    MouseToggleKey->setText( QString::null );
    FreeLookKey->setText( QString::null );
    KeyBinder->changeTab( mouse, tr( "Mouse" ) );
    EyepointButtonGroup2->setTitle( QString::null );
    MoveRightKey->setText( QString::null );
    MoveUpKey->setText( QString::null );
    MoveLeftKey->setText( QString::null );
    TurnLeftKey->setText( QString::null );
    TurnRightKey->setText( QString::null );
    MoveDownKey->setText( QString::null );
    PitchUpKey->setText( QString::null );
    PitchDownKey->setText( QString::null );
    MoveBackwardKey->setText( QString::null );
    MoveForwardKey->setText( QString::null );
    EyepointButtonGroup->setTitle( QString::null );
    ForwardButton->setText( tr( "Forward" ) );
    BackwardButton->setText( tr( "Backward" ) );
    LeftButton->setText( tr( "Strafe Left" ) );
    RightButton->setText( tr( "Strafe Right" ) );
    TurnRightButton->setText( tr( "Turn Right" ) );
    UpButton->setText( tr( "Up" ) );
    DownButton->setText( tr( "Down" ) );
    PitchUpButton->setText( tr( "Pitch Up" ) );
    PitchDownButton->setText( tr( "Pitch Down" ) );
    TurnLeftButton->setText( tr( "Turn Left" ) );
    KeyBinder->changeTab( eyepoint, tr( "Eyepoint" ) );
}

